### ISSUE TITLE
how to fix this error SharedArrayBuffer 

### ISSUE THREAD

**Issue by qadeesz** [fireship-io/react-wasm-gif-maker#1]
ffmpeg-core.js:22 Uncaught (in promise) ReferenceError: SharedArrayBuffer is not defined
    at ffmpeg-core.js:22
    at Object.load (ffmpeg.js:1408)
    at async load (App.js:38)

![image](https://user-images.githubusercontent.com/25366607/132130549-81407086-8ebf-4ad9-8a7c-aa22dc020f54.png)

**Comment by qadeesz** [comment]
"dependencies": {
    "@ffmpeg/core": "^0.8.3",
    "@ffmpeg/ffmpeg": "^0.9.4",
    "react": "^17.0.0",
    "react-dom": "^17.0.0"
  },

**Comment by zerefdev** [comment]
@qadeesz 

> SharedArrayBuffer is only available to pages that are [cross-origin isolated](https://developer.chrome.com/blog/enabling-shared-array-buffer/#cross-origin-isolation). So you need to host [your own server](https://github.com/ffmpegwasm/ffmpegwasm.github.io/blob/main/server/server.js) with `Cross-Origin-Embedder-Policy: require-corp` and `Cross-Origin-Opener-Policy: same-origin` headers to use ffmpeg.wasm.

**Edit:**
Example using Next.js
_next.config.js_
```js
module.exports = {
  reactStrictMode: true,
  headers() {
    return [
      {
        source: '/',
        headers: [
          {
            key: 'Cross-Origin-Embedder-Policy',
            value: 'require-corp'
          },
          {
            key: 'Cross-Origin-Opener-Policy',
            value: 'same-origin'
          }
        ]
      }
    ];
  }
};
```

**Comment by qadeesz** [comment]
@zerefdev  
Thanks

**Comment by apoorvpandey0** [comment]
> @qadeesz
> 
> > SharedArrayBuffer is only available to pages that are [cross-origin isolated](https://developer.chrome.com/blog/enabling-shared-array-buffer/#cross-origin-isolation). So you need to host [your own server](https://github.com/ffmpegwasm/ffmpegwasm.github.io/blob/main/server/server.js) with `Cross-Origin-Embedder-Policy: require-corp` and `Cross-Origin-Opener-Policy: same-origin` headers to use ffmpeg.wasm.
> 
> **Edit:** Example using Next.js _next.config.js_
> 
> ```js
> module.exports = {
>   reactStrictMode: true,
>   headers() {
>     return [
>       {
>         source: '/',
>         headers: [
>           {
>             key: 'Cross-Origin-Embedder-Policy',
>             value: 'require-corp'
>           },
>           {
>             key: 'Cross-Origin-Opener-Policy',
>             value: 'same-origin'
>           }
>         ]
>       }
>     ];
>   }
> };
> ```

Hi, how to do this for a simple react app, I'm just trying to follow the tutorial?

1. I installed next using "npm install next" and
2.  then added the above code to next.config.js in my src folder
Is there any extra step I need to do? I'm very new to JS

**Comment by sagnikghoshcr7** [comment]
@qadeesz 
Check this https://github.com/sagnikghoshcr7/gif-maker
